import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import Navigation from "../../components/Navigation";
import Footer from "../../components/Footer";
import { fontVariables } from '@/config/fonts';
import I18nProvider from '@/components/I18nProvider';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'es' }];
}

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  // Await the params to get the locale
  const { locale } = await params;
  const lang = locale || 'en';

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} ${fontVariables} bg-[#f3f1e5] min-h-screen flex flex-col font-montserrat`}>
        <I18nProvider locale={lang}>
          <Navigation />
          <main className="pt-16">{children}</main>
          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}